---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sftp-server
  labels:
    name: sftp-server
  namespace: mw-sftp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: sftp-server
        version: v1
      annotations:
        container.apparmor.security.beta.kubernetes.io/sftp-server: runtime/default
    spec:
      volumes:
      - name: sftp-server-pv-storage
        persistentVolumeClaim:
          claimName: sftp-server-pv-claim
      containers:
      - name: sftp-server
        image: eu.gcr.io/moss-work/sftp-server:${VERSION}
        ports:
        - containerPort: 22
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: sftp-server-sec
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: sftp-server-sec
              key: password
        - name: OWNER_ID
          value: "1000"
        - name: FOLDER
          value: /data
        volumeMounts:
        - mountPath: /data
          name: sftp-server-pv-storage
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-server-svc
  namespace: mw-sftp
  labels:
    name: sftp-server-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 35.190.144.151
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    name: sftp-server
