---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${IMAGE_NAME}-pv-volume
  namespace: ${NAMESPACE}
spec:
  capacity:
    storage: ${STORAGE_CAP}Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "${NAMESPACE}-pd1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${IMAGE_NAME}-pv-claim
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${STORAGE_CAP}Gi
