---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${IMAGE_NAME}
  labels:
    name: ${IMAGE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ${IMAGE_NAME}
        version: v1
      annotations:
        container.apparmor.security.beta.kubernetes.io/sftp-server: runtime/default
    spec:
      volumes:
      - name: ${IMAGE_NAME}-pv-storage
        persistentVolumeClaim:
          claimName: ${IMAGE_NAME}-pv-claim
      containers:
      - name: ${IMAGE_NAME}
        image: ${BUILD_IMAGE}:${VERSION}
        ports:
        - containerPort: 22
        env:
        - name: USERNAME
          value: laika
        - name: PASSWORD
          value: Passw0rd
        - name: OWNER_ID
          value: "1000"
        - name: FOLDER
          value: /data
        volumeMounts:
        - mountPath: /data
          name: ${IMAGE_NAME}-pv-storage
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
---
apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}-svc
  namespace: ${NAMESPACE}
  labels:
    name: ${IMAGE_NAME}-svc
spec:
  type: LoadBalancer
  loadBalancerIP: ${STATIC_IP}
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    name: ${IMAGE_NAME}
